package natsmqtt5_test

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"io/fs"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strconv"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// The conformance table (conformance/mqtt5-statements.tsv) and the counts in
// CONFORMANCE.md are checked against the code, so that neither can claim what the
// tests do not show. A row says a statement is TESTED only if each test it names
// exists and cites the statement's id (in its name, its doc comment or its body).
// The counts tables in CONFORMANCE.md are recomputed from the rows; set
// UPDATE_CONFORMANCE=1 to rewrite them after the rows change.

const (
	conformanceTSV   = "conformance/mqtt5-statements.tsv"
	conformanceDoc   = "CONFORMANCE.md"
	countsBeginMark  = "<!-- counts:begin (generated by conformance_table_test.go; UPDATE_CONFORMANCE=1 rewrites it) -->"
	countsEndMark    = "<!-- counts:end -->"
	classTested      = "TESTED"
	classNotApplic   = "NOT-APPLICABLE"
	classClientOnly  = "CLIENT-ONLY"
	verdictMet       = "met"
	verdictNA        = "n/a"
	verdictViolated  = "VIOLATED"
	verdictUnsure    = "UNSURE"
	evidenceTestsSep = " | tests: "
)

type statementRow struct {
	id, section, binds, class, verdict, roadmap, evidence string
}

func readStatements(t *testing.T) []statementRow {
	t.Helper()
	raw, err := os.ReadFile(conformanceTSV)
	require.NoError(t, err)
	lines := strings.Split(strings.TrimRight(string(raw), "\n"), "\n")
	require.Equal(t, "id\tsection\tbinds\tclass\tverdict\troadmap\tevidence", lines[0], "the column format")
	var rows []statementRow
	seen := map[string]bool{}
	for _, l := range lines[1:] {
		f := strings.Split(l, "\t")
		require.Len(t, f, 7, "seven columns in %q", l)
		require.False(t, seen[f[0]], "%s appears twice", f[0])
		seen[f[0]] = true
		rows = append(rows, statementRow{f[0], f[1], f[2], f[3], f[4], f[5], f[6]})
	}
	return rows
}

var statementIDText = regexp.MustCompile(`MQTT-\d+(?:\.\d+)*-\d+`)

// underscoreID turns MQTT-3.3.4-1 into MQTT_3_3_4_1, the form a test name uses.
func underscoreID(id string) string {
	i := strings.LastIndex(id, "-")
	return strings.NewReplacer("-", "_", ".", "_").Replace(id[:i]) + "_" + id[i+1:]
}

// nameCites reports whether a test name carries id in underscore form, and not
// as the front of a longer number or section (MQTT_5_0_4_8_2 is §4.8.2).
func nameCites(name, id string) bool {
	u := underscoreID(id)
	for from := 0; ; {
		i := strings.Index(name[from:], u)
		if i < 0 {
			return false
		}
		end := from + i + len(u)
		isDigit := func(i int) bool { return i < len(name) && name[i] >= '0' && name[i] <= '9' }
		if !isDigit(end) && !(end < len(name) && name[end] == '_' && isDigit(end+1)) {
			return true
		}
		from += i + 1
	}
}

// citingTests maps each Test function of the module to the text it is judged on:
// its doc comment and body.
func testFunctions(t *testing.T) map[string]string {
	t.Helper()
	funcs := map[string]string{}
	err := filepath.WalkDir(".", func(p string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() && (d.Name() == ".git" || d.Name() == "testdata") {
			return filepath.SkipDir
		}
		if d.IsDir() || !strings.HasSuffix(p, "_test.go") {
			return nil
		}
		src, err := os.ReadFile(p)
		if err != nil {
			return err
		}
		fset := token.NewFileSet()
		f, err := parser.ParseFile(fset, p, src, parser.ParseComments)
		if err != nil {
			return err
		}
		for _, decl := range f.Decls {
			fd, ok := decl.(*ast.FuncDecl)
			if !ok || fd.Recv != nil || !strings.HasPrefix(fd.Name.Name, "Test") {
				continue
			}
			start := fd.Pos()
			if fd.Doc != nil {
				start = fd.Doc.Pos()
			}
			funcs[fd.Name.Name] = string(src[fset.Position(start).Offset:fset.Position(fd.End()).Offset])
		}
		return nil
	})
	require.NoError(t, err)
	return funcs
}

func (r statementRow) cites(funcs map[string]string, test string) bool {
	text, ok := funcs[test]
	if !ok {
		return false
	}
	if nameCites(test, r.id) {
		return true
	}
	for _, m := range statementIDText.FindAllString(text, -1) {
		if m == r.id {
			return true
		}
	}
	return false
}

// namedTests are the test names in a row's evidence: all of it for a TESTED row,
// what follows " | tests: " for a NOT-APPLICABLE one.
func (r statementRow) namedTests() []string {
	ev := r.evidence
	if r.class == classNotApplic {
		i := strings.Index(ev, evidenceTestsSep)
		if i < 0 {
			return nil
		}
		ev = ev[i+len(evidenceTestsSep):]
	}
	if i := strings.Index(ev, " (+"); i >= 0 {
		ev = ev[:i]
	}
	return strings.Fields(ev)
}

func TestEveryConformanceRowIsBackedByATestThatCitesIt(t *testing.T) {
	rows := readStatements(t)
	funcs := testFunctions(t)
	for _, r := range rows {
		switch r.class {
		case classTested:
			assert.Equal(t, verdictMet, r.verdict, "%s: a tested row is met", r.id)
			named := r.namedTests()
			if assert.NotEmpty(t, named, "%s is TESTED and names no test", r.id) {
				for _, name := range named {
					assert.True(t, r.cites(funcs, name), "%s: %s does not exist or does not cite the id", r.id, name)
				}
			}
		case classNotApplic:
			assert.Equal(t, verdictNA, r.verdict, r.id)
			assert.NotEmpty(t, r.evidence, "%s: say why it does not apply", r.id)
			for _, name := range r.namedTests() {
				assert.True(t, r.cites(funcs, name), "%s: %s does not exist or does not cite the id", r.id, name)
			}
		case classClientOnly:
			assert.Equal(t, verdictNA, r.verdict, r.id)
			assert.Equal(t, "C", r.binds, "%s: only a statement that binds a Client alone is CLIENT-ONLY", r.id)
		default:
			t.Errorf("%s: unknown class %q", r.id, r.class)
		}
	}
}

// A statement the broker violates, or that nobody has settled, must be fixed or
// written up in CONFORMANCE.md before it can be in the table at all.
func TestNoConformanceStatementIsViolatedOrUnsure(t *testing.T) {
	doc, err := os.ReadFile(conformanceDoc)
	require.NoError(t, err)
	for _, r := range readStatements(t) {
		if r.verdict == verdictViolated || r.verdict == verdictUnsure {
			assert.Contains(t, string(doc), r.id,
				"%s is %s in the table and CONFORMANCE.md does not list it", r.id, r.verdict)
			t.Errorf("%s is %s: %s", r.id, r.verdict, r.evidence)
		}
	}
}

// An evidence test that a NOT-APPLICABLE or CLIENT-ONLY row names must also be
// a feature the ROADMAP.md knows, when the row says the feature is on it.
func TestConformanceRowsPointAtRoadmapEntriesThatExist(t *testing.T) {
	roadmap, err := os.ReadFile("ROADMAP.md")
	require.NoError(t, err)
	for _, r := range readStatements(t) {
		if r.roadmap != "" {
			assert.Contains(t, string(roadmap), "## "+r.roadmap, "%s names a roadmap entry that is not there", r.id)
		}
	}
}

// countsBlock renders the tables CONFORMANCE.md carries between its markers.
func countsBlock(rows []statementRow) string {
	count := func(pred func(statementRow) bool) int {
		n := 0
		for _, r := range rows {
			if pred(r) {
				n++
			}
		}
		return n
	}
	byClass := func(c string) int { return count(func(r statementRow) bool { return r.class == c }) }
	byVerdict := func(v string) int { return count(func(r statementRow) bool { return r.verdict == v }) }
	byBinds := func(b string) int { return count(func(r statementRow) bool { return r.binds == b }) }
	var b strings.Builder
	fmt.Fprintf(&b, "%d statements.\n\n", len(rows))
	b.WriteString("| Class | Meaning | Count |\n|---|---|---|\n")
	fmt.Fprintf(&b, "| TESTED | a test drives the broker (or the codec) and cites the statement | %d |\n", byClass(classTested))
	fmt.Fprintf(&b, "| NOT-APPLICABLE | behind a feature the broker does not offer, or cannot be violated by a request | %d |\n", byClass(classNotApplic))
	fmt.Fprintf(&b, "| CLIENT-ONLY | binds only a Client, and no test of the broker cites it | %d |\n", byClass(classClientOnly))
	b.WriteString("\n| Verdict | Count |\n|---|---|\n")
	fmt.Fprintf(&b, "| met | %d |\n| n/a | %d |\n| VIOLATED | %d |\n| UNSURE | %d |\n",
		byVerdict(verdictMet), byVerdict(verdictNA), byVerdict(verdictViolated), byVerdict(verdictUnsure))
	b.WriteString("\n| Binds | Count |\n|---|---|\n")
	fmt.Fprintf(&b, "| Server | %d |\n| Client and Server | %d |\n| Client | %d |\n", byBinds("S"), byBinds("CS"), byBinds("C"))
	return b.String()
}

func TestTheCountsInConformanceMdAreTheTables(t *testing.T) {
	want := countsBlock(readStatements(t))
	raw, err := os.ReadFile(conformanceDoc)
	require.NoError(t, err)
	doc := string(raw)
	begin := strings.Index(doc, countsBeginMark)
	end := strings.Index(doc, countsEndMark)
	require.True(t, begin >= 0 && end > begin, "CONFORMANCE.md needs the %q ... %q markers", countsBeginMark, countsEndMark)
	have := doc[begin+len(countsBeginMark)+1 : end]
	if have == want {
		return
	}
	if ok, _ := strconv.ParseBool(os.Getenv("UPDATE_CONFORMANCE")); ok {
		updated := doc[:begin+len(countsBeginMark)+1] + want + doc[end:]
		require.NoError(t, os.WriteFile(conformanceDoc, []byte(updated), 0o644))
		return
	}
	t.Fatalf("the counts in CONFORMANCE.md are not the table's; run UPDATE_CONFORMANCE=1 go test -run TestTheCountsInConformanceMdAreTheTables\nwant:\n%s\nhave:\n%s", want, have)
}

// Every statement id a test cites is one the table knows, so a typo in a test name
// does not pass for coverage.
func TestEveryStatementIDATestCitesIsInTheTable(t *testing.T) {
	known := map[string]bool{}
	for _, r := range readStatements(t) {
		known[r.id] = true
	}
	funcs := testFunctions(t)
	names := make([]string, 0, len(funcs))
	for n := range funcs {
		names = append(names, n)
	}
	sort.Strings(names)
	for _, n := range names {
		for _, id := range statementIDText.FindAllString(funcs[n], -1) {
			assert.True(t, known[id], "%s cites %s, which is not a statement of the specification's table", n, id)
		}
	}
}
